#!/bin/bash
#
# Compress NIFTI files
#
# TODO :: add option parsing
#      :: add pattern (dont convert all files!)
#      :: add speed option for gzip
#      :: maybe add option to decompress?

[ ! $(which brew) ] && /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
[ ! $(which parallel) ] && brew install parallel

parallel -k --link --bar gzip {} ::: $(find . -type f -name '*.nii')